---
# Source: canary-app/templates/all.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: canary-app
      app.kubernetes.io/instance: canary-app
---
# Source: canary-app/templates/all.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
automountServiceAccountToken: false
---
# Source: canary-app/templates/all.yaml
apiVersion: v1
kind: Secret
metadata:
  name: 'canary-app-extra'
stringData:
  hello: world

---
# Source: canary-app/templates/all.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
data:
  LOG_LEVEL: "debug"
  MAX_CONN: "100"
---
# Source: canary-app/templates/all.yaml
apiVersion: v1
kind: Service
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
---
# Source: canary-app/templates/all.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
spec:
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: canary-app
      app.kubernetes.io/instance: canary-app
  template:
    metadata:
      annotations:
        checksum/config: 4d024c48fa184075175b66865fe83006f4d56f3ab9a97aa9701e117c15b94951
      labels:
        app.kubernetes.io/name: canary-app
        app.kubernetes.io/instance: canary-app
    spec:
      serviceAccountName: canary-app
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      containers:
        - name: canary-app
          image: "nginxinc/nginx-unprivileged:1.27-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: canary-app
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi
---
# Source: canary-app/templates/all.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
# Source: canary-app/templates/all.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-app
  labels:
    helm.sh/chart: canary-app-0.1.0
    app.kubernetes.io/name: canary-app
    app.kubernetes.io/instance: canary-app
    app.kubernetes.io/version: "1.27-alpine"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "web"
    app.kubernetes.io/part-of: "canary"
    team: platform
  annotations:
    owner: sre@example.com
spec:
  ingressClassName: nginx
  rules:
    - host: "canary.example.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: canary-app
                port:
                  name: http
